id: P55530E5D
initial_creation_type: input
source_metadata:
  title: Sādhanas Series
  language: zh
  description: 'Lotsawa House presents the following sādhanas (sgrub thabs). (Please
    note that you may need to receive empowerment, transmission and instructions from
    a qualified lineage-holder before putting these sādhanas into practice):'
  volume:
    7091f26fab9c47dd8774108eb251ab60:
      title: Acala Sādhana
      parent: Acala
    251dcf51f7134a368166b51eaa775900:
      title: A Daily Practice of Buddha Akṣobhya
      parent: Akṣobhya
    8c9f42a3f81d458d997b5e32cba4b15a:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Amitāyus
    5103d592a6bd426381124083386700f8:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Amitāyus
    dbd85ce33ecd419ba30a3fc1be44c58b:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Amitāyus
    6024df77810343658da2cd7e9b3edbd2:
      title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of
        Great Compassion & Mahāmudrā in Union'
      parent: Avalokiteśvara
    d59b649faf974935872b17343d078d4d:
      title: Visualization and Mantra Recitation of the Great Compassionate One
      parent: Avalokiteśvara
    fed47520557542ffb36478888cb836c5:
      title: Visualization and Recitation of the Six-Syllable Mantra of Avalokiteśvara
      parent: Avalokiteśvara
    67e390c3360a4cf1a31b601acb449761:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Avalokiteśvara
    f92f2697aeb14623a8ef1981f7d36ac8:
      title: 'The Sādhana of the Five Self-Arisen Noble Brothers: An Instruction in
        the Union of Generation and Completion'
      parent: Avalokiteśvara
    796df902db4f442b97687e0daceb865f:
      title: 'Far-Reaching Benefit of Beings, Extensive as the Sky: Visualization
        and Mantra Recitation of the Great Compassionate One'
      parent: Avalokiteśvara
    310c0e333e7c42d99a08003deb6c593e:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Buddha Śākyamuni
    9f2fa90749b24b2dbb07ec460e8f412d:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Buddha Śākyamuni
    f145f7650336470eb5faa013a3c162e7:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Buddha Śākyamuni
    35f595121bb74c1fabceedcee11ae682:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Buddha Śākyamuni
    48614cc3a14d4d14ba83c2c0c517fcbc:
      title: The Daily Practice of the Secret Sādhana of Dorje Drolö
      parent: Dorje Drolö
    086a11e238404e30a48ad6912b42f0b6:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Dorje Drolö
    7c3e6346191e4d8da905a43ca7566f6b:
      title: Extremely Secret Unelaborate Daily Sādhana for the Heart Practice of
        the Great Demon-Slayer
      parent: Dükyi Shechen
    368733eae7484314937988ca70480338:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Guru Dewa Chenpo
    4eb2485ff3804eb1b782aba190a16dc2:
      title: Daily Practice of Guru Drakpo
      parent: Guru Drakpo
    4fc9b85efa874db3a6194a24368da15c:
      title: Increasing Intelligence – Sealed with Profundity
      parent: Guru Loden Chokse
    4556371e5b4344a18b61c44e6272e9c5:
      title: Daily Practice of Hayagrīva
      parent: Hayagrīva
    6f7e63f7043642c29e1e169f8a6ec51c:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Hayagrīva
    220f693491b548e08fc0cd3cf33c3568:
      title: 'The Falling Rain of Blessings: A Brief Daily Practice of the Wealth
        Deity White Jambhala'
      parent: Jambhala
    749ebb9d63f6421796969428a1486839:
      title: A Sādhana of Jambhala
      parent: Jambhala
    f5144e98916946afb88c24378913c221:
      title: Daily Practice of Kagyé
      parent: Kagyé
    fd1e823b9bf146a68a413c0b833970aa:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Kurukullā
    8fdb563bbbc348e5a7443ffe8e8ab8b1:
      title: A Sādhana of Kurukullā
      parent: Kurukullā
    1607a64cb2ce4a06868220d39f3c022e:
      title: A Daily Practice of Lama Sangdü
      parent: Lama Sangdü
    f8001668fed344098e9304ccc30d65b5:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Lama Sangdü
    224fc33420134d53ad7fa5d8520890f6:
      title: Light from the Wisdom Sun
      parent: Mañjuśrī
    5bdcd9acb70d4c44b1ff3927bf878fd4:
      title: A Sādhana of Golden Mañjughoṣa
      parent: Mañjuśrī
    48510968ecab41b8bdc6425471a970bd:
      title: 'Swift Bestowal of Blessings: A Peaceful Sādhana of Mañjuśrī'
      parent: Mañjuśrī
    4003da3046744891b52e3a78228809d8:
      title: A Brief Mañjuśrī Sādhana
      parent: Mañjuśrī
    11ba111708a54933b06f50460cb6b977:
      title: Sādhana of Mañjughoṣa
      parent: Mañjuśrī
    4854f57ba17d46df9e3bc83238db4fec:
      title: A Sādhana of Mārīcī
      parent: Mārīcī
    41b5f54b47e04104bb6f168a34c76d73:
      title: Sādhana of Mārīcī
      parent: Mārīcī
    6de92aab25cd48ef8db98dd7c14d853a:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Medicine Buddha
    3be5a4693f3548b496f343493e8f8f29:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Medicine Buddha
    246f10de3a654ca0856c14ede2084078:
      title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
      parent: Medicine Buddha
    b3aac2d4a4e840f8a0ed4821d0c20e0d:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Peaceful & Wrathful Deities
    ee30628e424f47d7b9e0e65b9b807666:
      title: A Brief Visualization and Recitation of the Great Mother Prajñāpāramitā
      parent: Prajñāpāramitā
    d8f46c162c1e473e90f5c2d2d29ca1c6:
      title: A Sādhana of Tārā Sarasvatī
      parent: Sarasvatī
    622e273fdd9a46cc848f04714a6e2e72:
      title: A Sādhana of White Sarasvatī
      parent: Sarasvatī
    b673eefbe7ed4f998058c408a606fd5b:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sarasvatī
    995539751576459c8ca2d13cd52b9145:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Siṃhamukhā
    7861d67bf52c4970bc4f171f35b78a3d:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sitātapatrā
    19c413cc0d304c47bd5037adbb419634:
      title: 'The Swift Steed of Garuḍa, King of Birds: An Instruction for Travelling
        to Sukhāvatī: A Visualization and Recitation of Uṣnīṣa-Sitātapatrā'
      parent: Sitātapatrā
    d4adaf94451242e38eaff20053b651f4:
      title: A Sādhana of Sitātapatrā
      parent: Sitātapatrā
    19e769fe88db4b3cac28385a6d286609:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Takhyung Barwa
    637fe0f6eaa240d199a1831c40fa1b2e:
      title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of
        Immortality
      parent: Tārā
    6d04119ec7604923a4824a49c5097dbd:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Tārā
    6d5fba1498e149d796a94ebfba364fd3:
      title: Concise White Tārā Sādhana
      parent: Tārā
    2a8f918b62924094bcf2fcc2dbb4a170:
      title: 'Swift Enchantment of the Three Realms: A Sādhana of Red Tārā'
      parent: Tārā
    2e579461616b434dafa961b34528db7e:
      title: 'A Shower of Blessings: A Sādhana of Blue-Green Tārā'
      parent: Tārā
    97ef3d2ee85746ffbcf7167bc7746564:
      title: A Daily Practice of Ucchuṣma
      parent: Ucchuṣma
    8ba93a4a69ac4f6d84b81791dcfaf1dc:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      parent: Ucchuṣma
    f2eb360895aa4c20a537c5328dda68d9:
      title: Daily Practice of Vajrakīla
      parent: Vajrakīla
    4602690380af4a879fb9cd400d0d7c4f:
      title: The Essential Daily Practice of Vajrakīla
      parent: Vajrakīla
    8e547fe6f82b4ab5837cb8c1d79761a4:
      title: 'The Accomplishment of Supreme Enlightened Activity: A Recitation Manual
        for The Vajrakīla Root Tantra Section'
      parent: Vajrakīla
    69481e83c0884a85953ddf1499442ca9:
      title: 'Inlaid Jewels: Addenda to the ''Neck-Pouch Dagger’ (Purba Gulkhukma)
        Cycle'
      parent: Vajrakīla
    b6eed947dfe04f3499a9636ac8dd6170:
      title: The Single Mind Kīla Practice, Part of the 'Neck-Pouch Dagger’ (Purba
        Gulkhukma) Cycle
      parent: Vajrakīla
    9c68434174804b1f8774c0b1baa4007b:
      title: The Wisdom Mind Practice of One Kīla
      parent: Vajrakīla
    3e8b06154f9f46d5a4796e488b0673b0:
      title: Concise Daily Practice of Vajrasattva
      parent: Vajrasattva
    87ae7e7f307e4a8a8c8a297725e4eac5:
      title: Brief Vajrasattva Visualisation and Mantra Recitation
      parent: Vajrasattva
    075d46e8d8eb465185136826bacdb8da:
      title: 'The Cintāmaṇi (Wish-Fulfilling Jewel) Instruction: A Sādhana of the
        Glorious Vajrasattva, a Method of Purification and Accomplishment for Both
        Self and Others'
      parent: Vajrasattva
    67a28b26ecc04332b05df0a65b68f41f:
      title: Daily Practice of Mañjuśrī Yamāntaka
      parent: Yamāntaka
    267bc2daf4104acf91c5b816b45f1ffd:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Yeshe Tsogyal
    8a594dfd199c493bad98012ac6c99fb6:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Yumka Dechen Gyalmo
    ccdba26b73e4498899f7b8210a2b2f5d:
      title: 'The Light of Primordial Wisdom: An Instruction Manual for the Primordially
        Pure Perfection Stage of the Powerful & Wrathful Dorje Drolö, Conqueror of
        Demons'
      parent: Commentaries
    5efbeb62e15346ffa0f68f5db161f573:
      title: A Daily Practice of Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-03-01T05:36:59.660912'
last_modified_at: '2022-03-01T05:36:59.660915'
